fileVersion: 1
id: "9"
mappingDefinitions:
  SOURCE:
    database: SNOWFLAKE_SAMPLE_DATA
    schema: TPCH_SF100
  TARGET:
    database: COALESCE_DB
    schema: SALES_SF100_PROD
  UTILITIES:
    database: UTIL_DB
    schema: PUBLIC
name: Production
type: Environment
